# Generated by Django 3.2.12 on 2022-04-08 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='lisk_count',
            new_name='like_count',
        ),
    ]
